### 새가족 등록
POST http://localhost:8080/api/v2/new-families/register
Content-Type: application/json

{
  "name": "새가족2",
  "phoneNumber":"010-1234-5678",
  "birth": "2000-10-16",
  "sex": "MALE",
  "grade": 9,
  "visitDate": "2024-06-01",
  "newFamilyGroupId": null,
  "etc": {
    "school": "서울대학교 감자학과 6학년",
    "introducer": "박똘똘",
    "isFirstChurch": false,
    "address": "감자밭",
    "latestChurch": "온누리교회",
    "visitReason": "아는 사람 소개로",
    "relationshipWithJesus": "잘 모른다",
    "hasCertaintityOfSalvation": false,
    "comment": "이 친구는 짜장면을 좋아합니다"
  }
}

### 새가족 순장 배정
POST http://localhost:8080/api/v2/new-families/2/assign-new-family-group
Content-Type: application/json

{
  "newFamilyGroupId": 1
}

### 등반
POST http://localhost:8080/api/v2/new-families/2/promote
Content-Type: application/json

{
  "promoteDate": "2024-06-09",
  "smallGroupId": 1
}

### 라인업
POST http://localhost:8080/api/v2/new-families/1/line-up
Content-Type: application/json

{
  "smallGroupId": 1,
  "promoteDate": "2024-06-09"
}

### 라인아웃
POST http://localhost:8080/api/v2/new-families/4/line-out

### 새가족 복귀
POST http://localhost:8080/api/v2/lined-out-new-families/1/rollback
Content-Type: application/json

{
  "newFamilyGroupId": 1
}

### 새가족 정보 수정
POST http://localhost:8080/api/v2/new-families/1/update-info
Content-Type: application/json

{
  "name": "김똘똘2222",
  "phoneNumber":"010-1234-5678",
  "birth": "2000-10-16",
  "sex": "MALE",
  "grade": 9,
  "etc": {
    "school": "서울대학교 감자학과 6학년",
    "introducer": "박똘똘",
    "isFirstChurch": false,
    "address": "고구마밭",
    "latestChurch": "온누리교회",
    "visitReason": "아는 사람 소개로",
    "relationshipWithJesus": "잘 모른다",
    "hasCertaintityOfSalvation": false,
    "comment": "이 친구는 짜장면을 좋아합니다"
  }
}

### 새가족 출석 등록
POST http://localhost:8080/api/v2/new-family-attendance
Content-Type: application/json

{
  "date": "2024-06-10",
  "attendanceItems": [
    {
      "newFamilyId": 3,
      "status": "ATTEND",
      "reason": "크킄"
    },
    {
      "newFamilyId": 2,
      "status": "ATTEND",
      "reason": "크킄"
    }
  ]
}

### 로그인
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "foo",
  "password": "foo"
}

### 로그아웃
POST http://localhost:8080/api/auth/logout

### 새가족반 목록 조회
GET http://localhost:8080/api/v2/term/1/new-family-groups

### 새가족 목록 조회
GET http://localhost:8080/api/v2/new-families?newFamilyGroupId=1

### 등반자 목록 조회
GET http://localhost:8080/api/v2/promoted-new-families

### 새가족 이탈자 목록 조회
GET http://localhost:8080/api/v2/lined-out-new-families

### 순모임 목록 조회
GET http://localhost:8080/api/v2/term/1/small-groups

### 새가족 출석 조회
GET http://localhost:8080/api/v2/new-family-attendances?
    cursor=2025-06-19T20:09:52Z
    &limit=4
