### 새가족 등록
POST http://localhost:8080/api/v2/new-families/register
Content-Type: application/json

{
  "name": "김똘똘",
  "phoneNumber":"010-1234-5678",
  "birth": "2000-10-16",
  "gender": "MALE",
  "grade": 9,
  "visitDate": "2024-06-01",
  "newFamilyGroupId": 1,
  "etc": {
    "school": "서울대학교 감자학과 6학년",
    "introducer": "박똘똘",
    "isFirstChurch": false,
    "latestChurch": "온누리교회",
    "visitReason": "아는 사람 소개로",
    "relationshipWithJesus": "잘 모른다",
    "hasCertaintityOfSalvation": false,
    "comment": "이 친구는 짜장면을 좋아합니다"
  }
}

### 새가족 순장 배정
POST http://localhost:8080/api/v2/new-families/1/assign-new-family-group
Content-Type: application/json

{
  "newFamilyGroupId": 1
}

### 등반
POST http://localhost:8080/api/v2/new-families/1/promote
Content-Type: application/json

{
  "promoteDate": "2024-06-09",
  "smallGroupId": 1
}

### 라인업
POST http://localhost:8080/api/v2/new-families/1/line-up
Content-Type: application/json

{
  "smallGroupId": 1,
  "promoteDate": "2024-06-09"
}

### 라인아웃
POST http://localhost:8080/api/v2/new-families/1/line-out
