### 권한 1. 로그인
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "foo",
  "password": "foo"
}

### 권한 2. 로그아웃
POST http://localhost:8080/api/v1/auth/logout


### 인적정보 1. 새가족 등록
POST http://localhost:8080/api/v1/new-families/register
Content-Type: application/json

{
  "name": "고길동",
  "sex": "MALE",
  "phoneNumber":"010-1234-5678",
  "birth": "2003-03-03",
  "visitDate": "2024-09-01",
  "grade": 3,
  "newFamilyGroupId": null,
  "etc": {
    "school": "감자대학교 감자학과 1학년",
    "introducer": "홍길동",
    "isFirstChurch": "NO",
    "latestChurch": "온누리교회",
    "visitReason": "DISCIPLE_TRAINING",
    "relationshipWithJesus": "LORD",
    "hasCertaintityOfSalvation": "YES",
    "comment": "이 친구는 짜장면을 좋아합니다"
  }
}

### 인적정보 2. 새가족 수정
POST http://localhost:8080/api/v1/new-families/4/update
Content-Type: application/json

{
  "name": "고길동",
  "sex": "MALE",
  "phoneNumber":"010-1234-5678",
  "birth": "2003-03-03",
  "visitDate": "2024-09-01",
  "grade": 3,
  "newFamilyGroupId": 1,
  "etc": {
    "school": "감자대학교 감자학과 1학년",
    "introducer": "홍길동",
    "isFirstChurch": "NO",
    "latestChurch": "온누리교회",
    "visitReason": "DISCIPLE_TRAINING",
    "relationshipWithJesus": "LORD",
    "hasCertaintityOfSalvation": "YES",
    "comment": "이 친구는 짜장면을 좋아합니다",
    "lineUpMemo": "낯을 많이 가림"
  }
}

### 인적정보 3. 새가족 목록 조회
GET http://localhost:8080//api/v1/new-families?newFamilyGroupId=1

### 인적정보 4. 새가족 정보 조회
GET http://localhost:8080/api/v1/new-families/1

### 인적정보 5. 라인업 요청 목록
GET http://localhost:8080/api/v1/promote-candidate-new-families

### 인적정보 6. 임시 라인업 목록
GET http://localhost:8080/api/v1/temporary-lined-up-new-families

### 인적정보 7. 등반자 목록
GET http://localhost:8080/api/v1/promoted-new-families

### 인적정보 8. 내 정보
GET http://localhost:8080/api/v1/my-info

### 등반/라인업 1. 새가족 대량 라인업 요청
POST http://localhost:8080/api/v1/new-families/request-line-up
Content-Type: application/json

{
  "newFamilyIds": [4]
}

### 등반/라인업 2. 새가족 대량 후보순장 임시 라인업
POST http://localhost:8080/api/v1/new-families/temporary-line-up
Content-Type: application/json

{
  "content": [
    {
      "newFamilyId": 4,
      "temporarySmallGroupIds": [1]
    }
  ]
}

### 등반/라인업 3. 새가족 대량 라인업 ONLY
POST http://localhost:8080/api/v1/new-families/line-up
Content-Type: application/json

{
  "content": [
    {
      "newFamilyId": 3,
      "smallGroupId": 1
    }
  ]
}

### 등반/라인업 4. 새가족 대량 등반 ONLY
POST http://localhost:8080/api/v1/new-families/promote
Content-Type: application/json

{
  "content": [
    {
      "newFamilyId": 3,
      "promoteDate": "2024-09-13"
    }
  ]
}

### 출석 1. 새가족 목록 출석 조회
GET http://localhost:8080/api/v1/new-families/attendances

### 출석 2. 새가족 출석 체크
POST http://localhost:8080/api/v1/new-families/attendance-check
Content-Type: application/json

{
  "date": "2024-10-07",
  "attendanceItems": [
    {
      "newFamilyId": 4,
      "status": "ATTEND"
    },
    {
      "newFamilyId": 3,
      "status": "ATTEND"
    }
  ]
}

### 유출 1. 새가족 라인아웃
POST http://localhost:8080/api/v1/new-families/line-out
Content-Type: application/json

{
  "newFamilyIds": [8]
}

### 유출 2. 새가족 라인인
POST http://localhost:8080/api/v1/line-out-new-families/1/line-in

### 유출 3. 라인아웃 목록 조회
GET http://localhost:8080/api/v1/line-out-new-families

### 텀 1. 일반 순장 및 나무 목록 조회
GET http://localhost:8080/api/v1/terms/1/small-groups

### 텀 2. 새가족 순장 목록 조회
GET http://localhost:8080/api/v1/terms/1/new-family-groups

### 텀 3. 텀 목록
GET http://localhost:8080/api/v1/terms

### 텀 4. 활성화된 텀
GET http://localhost:8080/api/v1/terms/active-term
