### 0. 로그인
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "foo",
  "password": "foo"
}

### 인적정보 1. 새가족 등록
POST http://localhost:8080/api/v1/new-families/register
Content-Type: application/json

{
  "name": "고길동",
  "sex": "MALE",
  "phoneNumber":"010-1234-5678",
  "birth": "2003-03-03",
  "visitDate": "2024-09-01",
  "grade": 3,
  "newFamilyGroupId": null,
  "etc": {
    "school": "감자대학교 감자학과 1학년",
    "introducer": "홍길동",
    "isFirstChurch": "NO",
    "latestChurch": "온누리교회",
    "visitReason": "DISCIPLE_TRAINING",
    "relationshipWithJesus": "LORD",
    "hasCertaintityOfSalvation": "YES",
    "comment": "이 친구는 짜장면을 좋아합니다"
  }
}

### 인적정보 2. 새가족 수정
POST http://localhost:8080/api/v1/new-families/1/update
Content-Type: application/json

{
  "name": "고길동",
  "sex": "MALE",
  "phoneNumber":"010-1234-5678",
  "birth": "2003-03-03",
  "visitDate": "2024-09-01",
  "grade": 3,
  "newFamilyGroupId": 1,
  "etc": {
    "school": "감자대학교 감자학과 1학년",
    "introducer": "홍길동",
    "isFirstChurch": "NO",
    "latestChurch": "온누리교회",
    "visitReason": "DISCIPLE_TRAINING",
    "relationshipWithJesus": "LORD",
    "hasCertaintityOfSalvation": "YES",
    "comment": "이 친구는 짜장면을 좋아합니다",
    "lineUpMemo": "낯을 많이 가림"
  }
}

### 인적정보 3. 새가족 목록 조회
GET http://localhost:8080//api/v1/new-families

### 인적정보 4. 새가족 정보 조회
GET http://localhost:8080/api/v1/new-families/1

### 인적정보 5. 라인업 요청 목록
GET http://localhost:8080/api/v1/line-up-ready-new-families

### 텀 2. 새가족 순장 목록 조회
GET http://localhost:8080/api/v1/active-new-family-groups

### 등반/라인업 1. 새가족 라인업 요청(대량)
POST http://localhost:8080/api/v1/new-families/request-line-up
Content-Type: application/json

{
  "newFamilyIds": [2]
}
