### 새가족 출석 조회
GET https://wsangwook.com/api/v1/new-families/attendances

### 새가족 출석 체크
POST https://wsangwook.com/api/v1/new-families/attendance-check
Content-Type: application/json

{
  "date": "2024-10-07",
  "attendanceItems": [
    {
      "newFamilyId": 5,
      "status": "ATTEND"
    }
  ]
}
