### 텀 목록
GET https://wsangwook.com/api/v1/terms

### 활성 텀
GET https://wsangwook.com/api/v1/terms/active-term

### 일반 순장 및 나무 목록 조회
GET https://wsangwook.com/api/v1/terms/1/small-groups

### 새가족 순장 목록 조회
GET https://wsangwook.com/api/v1/terms/1/new-family-groups

### 순모임 생성
POST https://wsangwook.com/api/v1/terms/1/create-small-group
Content-Type: application/json

{
  "codyId": 14,
  "leaderUserId": 100,
  "memberUserIds": [374]
}

### 순모임 수정
POST https://wsangwook.com/api/v1/small-groups/60/update
Content-Type: application/json

{
  "memberUserIds": [373]
}

### 순모임 삭제
POST https://wsangwook.com/api/v1/small-groups/44/delete

### 순원 라인업 변경
POST https://wsangwook.com/api/v1/small-group-members/2/line-up-edit
Content-Type: application/json

{
  "targetSmallGroupId": 58
}

### 코디 추가
POST https://wsangwook.com/api/v1/terms/1/create-cody
Content-Type: application/json

{
  "codyUserId": 374
}

### 코디 삭제
POST https://wsangwook.com/api/v1/codies/11/delete

### 새가족반 추가
POST https://wsangwook.com/api/v1/terms/1/create-new-family-group
Content-Type: application/json

{
  "codyId": 14,
  "leaderUserId": 345,
  "memberUserIds": [346]
}

### 새가족반 제거
POST https://wsangwook.com/api/v1/new-family-groups/3/delete

### 새가족반 수정
POST https://wsangwook.com/api/v1/new-family-groups/1/update
Content-Type: application/json

{
  "memberUserIds": [360]
}

### 모든 리더쉽
GET https://wsangwook.com/api/v1/terms/1/all-leaders

### 코디 소속 인원
GET https://wsangwook.com/api/v1/codies/1/members

### 텀 별 인원 배정수
GET https://wsangwook.com/api/v1/terms/1/duty-distribution-count
