### 새가족 출석 조회
GET http://localhost:8080/api/v1/new-families/attendances

### 새가족 출석 체크
POST http://localhost:8080/api/v1/new-families/attendance-check
Content-Type: application/json

{
  "date": "2024-10-07",
  "attendanceItems": [
    {
      "newFamilyId": 3,
      "status": "ATTEND"
    }
  ]
}

### 그루터기 출석 체크
POST http://localhost:8080/api/v1/attendances/stump-attendance-check
Content-Type: application/json

{
  "termId": 1,
  "date": "2024-10-07",
  "attendanceItems": [
    {
      "userId": 4,
      "status": "ATTEND"
    },
    {
      "userId": 6,
      "status": "ATTEND"
    }
  ]
}

### 통계 갱신
POST http://localhost:8080/api/v1/run-batch-job
Content-Type: application/json

{
  "jobName": "helloWorldJob",
  "jobParameters": {
    "requestDate": "2024-10-10"
  }
}
