### 새가족 출석 조회
GET http://localhost:8080/api/v1/new-families/attendances

### 새가족 출석 체크
POST http://localhost:8080/api/v1/new-families/attendance-check
Content-Type: application/json

{
  "date": "2024-10-07",
  "attendanceItems": [
    {
      "newFamilyId": 3,
      "status": "ATTEND"
    }
  ]
}

### 그루터기 출석 체크
POST http://localhost:8080/api/v1/attendances/stump-attendance-check
Content-Type: application/json

{
  "date": "2024-10-07",
  "termId": 2,
  "attendanceItems": [
    {
      "userId": 8,
      "status": "ATTEND"
    },
    {
      "userId": 11,
      "status": "ATTEND"
    }
  ]
}

### 순모임 출석 체크
POST http://localhost:8080/api/v1/attendances/group-attendance-check
Content-Type: application/json

{
  "date": "2024-10-07",
  "groupType": "NEW_FAMILY_GROUP",
  "groupId": 5,
  "attendanceItems": [
    {
      "userId": 5,
      "status": "ATTEND"
    }
  ]
}

### 통계 갱신
POST http://localhost:8080/api/v1/run-batch-job
Content-Type: application/json

{
  "jobName": "visionReportJob",
  "jobParameters": {
    "requestDate": "2024-11-10"
  }
}
