### 출석 등록율 조회
GET http://localhost:8080/api/v1/attendances/attendance-register-rate?date=2024-10-20

### 새가족 출석 목록
GET http://localhost:8080/api/v1/new-families/attendances

### 비전 리포트 조회
GET http://localhost:8080/api/v1/vision-report?date=2024-10-20

### 비전 리포트 갱신
POST http://localhost:8080/api/v1/run-batch-job
Content-Type: application/json

{
  "jobName": "visionReportJob",
  "jobParameters": {
    "requestDate": "2024-10-20"
  }
}

### 그루터기 출석 체크
POST http://localhost:8080/api/v1/attendances/stump-attendance-check
Content-Type: application/json

{
  "date": "2024-10-20",
  "termId": 2,
  "attendanceItems": [
    {
      "userId": 7,
      "status": "ABSENT"
    },
    {
      "userId": 9,
      "status": "ATTEND"
    }
  ]
}

### 순모임 출석 체크
POST http://localhost:8080/api/v1/attendances/group-attendance-check
Content-Type: application/json

{
  "date": "2024-10-20",
  "termId": 2,
  "codyId": 8,
  "attendanceItems": [
    {
      "userId": 20,
      "status": "ATTEND"
    },
    {
      "userId": 10,
      "status": "ABSENT"
    },
    {
      "userId": 12,
      "status": "ATTEND"
    }
  ]
}

### 새가족 출석 체크
POST http://localhost:8080/api/v1/new-families/attendance-check
Content-Type: application/json

{
  "date": "2024-10-20",
  "attendanceItems": [
    {
      "newFamilyId": 5,
      "status": "ATTEND"
    },
    {
      "newFamilyId": 6,
      "status": "ABSENT"
    }
  ]
}
