### 주간 출석 통계 생성
POST http://localhost:8080/api/job
Content-Type: application/json

{
  "name": "weeklyAttendanceJob",
  "jobParameters": {
    "requestDate": "2023-10-01"
  }
}

### 텀 출석 통계 생성
POST http://localhost:8080/api/job
Content-Type: application/json

{
  "name": "termAttendanceJob",
  "jobParameters": {
    "termId": 1
  }
}
