### 담임 교역자 라인업
POST http://localhost:8080/api/v1/terms/2/assign-senior-pastor
Content-Type: application/json

{
  "userId": 9
}


### 부교역자 라인업
POST http://localhost:8080/api/v1/terms/2/assign-junior-pastor
Content-Type: application/json

{
  "userIds": [7]
}

### 코디 라인업
POST http://localhost:8080/api/v1/terms/2/assign-cody
Content-Type: application/json

{
  "userIds": [8]
}

### 일반 순장 라인업
POST http://localhost:8080/api/v1/terms/2/assign-small-group-leader
Content-Type: application/json

{
  "codyUserId": 8,
  "smallGroupLeaderUserIds": []
}

### 새가족 순장 라인업
POST http://localhost:8080/api/v1/terms/2/assign-new-family-group-leader
Content-Type: application/json

{
  "codyUserId": 8,
  "newFamilyGroupLeaderUserIds": [17]
}

### 일반 순원 라인업
POST http://localhost:8080/api/v1/terms/2/assign-small-group-member
Content-Type: application/json

{
  "leaderUserId": 15,
  "memberUserIds": []
}

### 새가족 순원 라인업
POST http://localhost:8080/api/v1/terms/2/assign-new-family-group-member
Content-Type: application/json

{
  "leaderUserId": 17,
  "memberUserIds": [16]
}

### 새가족 라인업
POST http://localhost:8080/api/v1/terms/2/assign-new-family
Content-Type: application/json

{
  "leaderUserId": 17,
  "newFamilyIds": [3]
}
