### 새 텀 추가
POST http://localhost:8080/api/v1/terms/create
Content-Type: application/json

{
  "name": "테슽흐2",
  "startDate": "2025-03-01",
  "endDate": "2025-08-31"
}

### 담임 교역자 라인업
POST http://localhost:8080/api/v1/terms/3/assign-senior-pastor
Content-Type: application/json

{
  "userId": 5
}


### 부교역자 라인업
POST http://localhost:8080/api/v1/terms/3/assign-junior-pastor
Content-Type: application/json

{
  "userIds": [9]
}

### 코디 라인업
POST http://localhost:8080/api/v1/terms/3/assign-cody
Content-Type: application/json

{
  "userIds": [4, 17]
}

### 일반 순장 라인업
POST http://localhost:8080/api/v1/terms/3/assign-small-group-leader
Content-Type: application/json

{
  "codyUserId": 4,
  "smallGroupLeaderUserIds": [5]
}


### 일반 순원 라인업
POST http://localhost:8080/api/v1/terms/3/assign-small-group-member
Content-Type: application/json

{
  "leaderUserId": 5,
  "memberUserIds": [6]
}

### 새가족 순장 라인업
POST http://localhost:8080/api/v1/terms/3/assign-new-family-group-leader
Content-Type: application/json

{
  "codyUserId": 4,
  "newFamilyGroupLeaderUserIds": [8]
}

### 새가족 순원 라인업
POST http://localhost:8080/api/v1/terms/3/assign-new-family-group-member
Content-Type: application/json

{
  "leaderUserId": 8,
  "memberUserIds": [12, 10]
}

### 새가족 라인업
POST http://localhost:8080/api/v1/terms/3/assign-new-family
Content-Type: application/json

{
  "leaderUserId": 8,
  "newFamilyIds": [3]
}

### 라인업 확정
POST http://localhost:8080/api/v1/terms/3/confirm-line-up
