### 새가족 목록
GET http://localhost:8080/api/v1/new-families

### 새가족 정보
GET http://localhost:8080/api/v1/new-families/1

### 라인업 요청 목록
GET http://localhost:8080/api/v1/promote-candidate-new-families

### 등반자 목록
GET http://localhost:8080/api/v1/promoted-new-families

### 새가족반 소속 일반 순원 목록
GET http://localhost:8080/api/v1/new-family-groups/4/new-family-group-members

### 라인아웃 목록
GET http://localhost:8080/api/v1/line-out-new-families

### 새가족 등록
POST http://localhost:8080/api/v1/new-families/register
Content-Type: application/json

{
  "name": "새가족응애",
  "sex": "MALE",
  "phoneNumber":"010-1234-5678",
  "birth": "2003-03-03",
  "visitDate": "2024-09-01",
  "grade": 3,
  "newFamilyGroupId": null,
  "etc": {
    "school": "감자대학교 감자학과 1학년",
    "introducer": "홍길동",
    "isFirstChurch": "NO",
    "latestChurch": "온누리교회",
    "visitReason": "DISCIPLE_TRAINING",
    "relationshipWithJesus": "LORD",
    "hasCertaintityOfSalvation": "YES",
    "comment": "이 친구는 짜장면을 좋아합니다"
  }
}

### 새가족 수정
POST http://localhost:8080/api/v1/new-families/1/update
Content-Type: application/json

{
  "name": "둘리",
  "sex": "MALE",
  "phoneNumber":"010-1234-5678",
  "birth": "2003-03-03",
  "visitDate": "2024-09-01",
  "grade": 3,
  "newFamilyGroupId": 1,
  "etc": {
    "school": "감자대학교 감자학과 1학년",
    "introducer": "홍길동",
    "isFirstChurch": "NO",
    "latestChurch": "온누리교회",
    "visitReason": "DISCIPLE_TRAINING",
    "relationshipWithJesus": "LORD",
    "hasCertaintityOfSalvation": "YES",
    "comment": "이 친구는 짜장면을 좋아합니다",
    "lineUpMemo": "낯을 많이 가림"
  }
}

### 라인업 요청
POST http://localhost:8080/api/v1/new-families/request-line-up
Content-Type: application/json

{
  "newFamilyIds": [1]
}

### 임시 라인업
POST http://localhost:8080/api/v1/new-families/temporary-line-up
Content-Type: application/json

{
  "content": [
    {
      "newFamilyId": 1,
      "temporarySmallGroupIds": [2]
    }
  ]
}

### 라인업
POST http://localhost:8080/api/v1/new-families/line-up
Content-Type: application/json

{
  "content": [
    {
      "newFamilyId": 1,
      "smallGroupId": 2
    }
  ]
}

### 등반
POST http://localhost:8080/api/v1/new-families/promote
Content-Type: application/json

{
  "content": [
    {
      "newFamilyId": 1,
      "promoteDate": "2024-09-13"
    }
  ]
}

### 라인아웃
POST http://localhost:8080/api/v1/new-families/line-out
Content-Type: application/json

{
  "newFamilyIds": [3]
}

### 라인인
POST http://localhost:8080/api/v1/line-out-new-families/1/line-in
