### 텀 목록
GET http://localhost:8080/api/v1/terms

### 활성 텀
GET http://localhost:8080/api/v1/terms/active-term

### 모든 리더쉽
GET http://localhost:8080/api/v1/terms/2/all-leaders

### 교역자 목록
GET http://localhost:8080/api/v1/terms/2/pastors

### 코디 목록
GET http://localhost:8080/api/v1/terms/2/codies

### 새가족반 목록
GET http://localhost:8080/api/v1/terms/2/new-family-groups

### 일반 순모임 목록
GET http://localhost:8080/api/v1/terms/1/small-groups

### 일반 순모임 목록 grouped by 코디
GET http://localhost:8080/api/v1/terms/1/small-groups-by-cody

### 직분별 인원 배정수
GET http://localhost:8080/api/v1/terms/3/duty-distribution-count

### 코디 소속 순모임(일반 & 새가족)
GET http://localhost:8080/api/v1/codies/17/groups

### 코디 소속 인원
GET http://localhost:8080/api/v1/codies/3/members

### 순모임 소속 순원
GET http://localhost:8080/api/v1/small-groups/3/small-group-members

### 교역자 추가
POST http://localhost:8080/api/v1/terms/2/create-pastor
Content-Type: application/json

{
  "pastorUserId": 8
}

### 교역자 삭제
POST http://localhost:8080/api/v1/pastors/1/delete

### 담임 교역자 변경
POST http://localhost:8080/api/v1/terms/2/switch-senior-pastor
Content-Type: application/json

{
  "targetSeniorPastorId": 2
}

### 코디 추가
POST http://localhost:8080/api/v1/terms/2/create-cody
Content-Type: application/json

{
  "codyUserId": 5
}

### 코디 수정
POST http://localhost:8080/api/v1/codies/9/update
Content-Type: application/json

{
  "smallGroupIds": [9, 10, 11]
}

### 코디 삭제
POST http://localhost:8080/api/v1/codies/3/delete

### 순모임 생성
POST http://localhost:8080/api/v1/terms/2/create-small-group
Content-Type: application/json

{
  "codyId": 8,
  "leaderUserId": 19,
  "memberUserIds": []
}

### 순모임 수정
POST http://localhost:8080/api/v1/small-groups/9/update
Content-Type: application/json

{
  "memberUserIds": []
}

### 순모임 삭제
POST http://localhost:8080/api/v1/small-groups/9/delete

### 새가족반 추가
POST http://localhost:8080/api/v1/terms/2/create-new-family-group
Content-Type: application/json

{
  "codyId": 3,
  "leaderUserId": 10,
  "memberUserIds": []
}

### 새가족반 제거
POST http://localhost:8080/api/v1/new-family-groups/8/delete

### 새가족반 수정
POST http://localhost:8080/api/v1/new-family-groups/1/update
Content-Type: application/json

{
  "memberUserIds": [11]
}

### 일반 순원 라인업 변경
POST http://localhost:8080/api/v1/small-group-members/1/line-up-edit
Content-Type: application/json

{
  "targetSmallGroupId": 2
}
