### 명부 생성(Documented)
POST http://localhost:8080/api/training
Content-Type: application/json

{
  "type": "DISCIPLE_SCHOOL_A",
  "name": "foo",
  "userIds": [2]
}

### 명부 수정
PUT http://localhost:8080/api/trainings/4
Content-Type: application/json

{
  "name":  "수정된 이름",
  "startDate": "2024-01-01",
  "endDate":  "2024-01-01",
  "userIds": [1, 3],
  "etc": "수정된 비고"
}

### 명부 삭제
DELETE http://localhost:8080/api/training/2

### 명부 복수 조회 by filter
GET http://localhost:8080/api/training?type=DISCIPLE_SCHOOL_A

### 명부 단건 조회
GET http://localhost:8080/api/trainings/5

### 제자훈련 생성
POST http://localhost:8080/api/discipleship
Content-Type: application/json

{
  "name": "하나라2",
  "startDate": "2018-09-01",
  "endDate": "2019-08-31",
  "userIds": [2]
}

### 제자훈련 수정
PUT http://localhost:8080/api/discipleship/2
Content-Type: application/json

{
  "name":  "수정된 훈련 이름",
  "etc": "수정된 비고",
  "userIds": [1, 3]
}

### 제자훈련 삭제
DELETE http://localhost:8080/api/discipleship/2

### 제자훈련 전체 조회
GET http://localhost:8080/api/discipleship

### 제자훈련 단건 조회
GET http://localhost:8080/api/discipleship/3
