### 전체 인원
GET http://localhost:8080/api/v1/users

### 유저
GET http://localhost:8080/api/v1/users/8

### 내 정보
GET http://localhost:8080/api/v1/my-info

### 파송자 목록 조회
GET http://localhost:8080/api/v1/dispatched-users

### 졸업자 목록 조회
GET http://localhost:8080/api/v1/graduated-users

### 라인아웃 유저 조회
GET http://localhost:8080/api/v1/line-out-users

### 유저 등록
POST http://localhost:8080/api/v1/users/register
Content-Type: application/json

{
  "name":  "김순장",
  "sex": "MALE",
  "phoneNumber":  "010-5555-6666",
  "birth": "1996-10-16",
  "grade":  10,
  "etc": "미나리",
  "smallGroupId": null
}

### 유저 수정
POST http://localhost:8080/api/v1/users/15/update
Content-Type: application/json

{
  "name":  "미나리",
  "sex": "MALE",
  "phoneNumber":  "010-5555-6666",
  "birth": "1996-10-16",
  "grade":  10,
  "etc": "청록 미나리식당",
  "smallGroupId": null
}

### 파송
POST http://localhost:8080/api/v1/users/dispatch
Content-Type: application/json

{
  "content": [
    {
      "userId": 7,
      "type": "MISSIONARY",
      "sendDate": "2024-09-01"
    },
    {
      "userId": 5,
      "type": "MISSIONARY",
      "sendDate": "2024-09-01"
    },
    {
      "userId": 11,
      "type": "MISSIONARY",
      "sendDate": "2024-09-01"
    },
    {
      "userId": 10,
      "type": "MISSIONARY",
      "sendDate": "2024-09-01"
    }
  ]
}

### 파송 복귀
POST http://localhost:8080/api/v1/dispatched-users/2/return

### 졸업
POST http://localhost:8080/api/v1/users/graduate
Content-Type: application/json

{
  "userIds": [3],
  "graduateDate": "2024-03-01"
}

### 라인아웃
POST http://localhost:8080/api/v1/users/line-out
Content-Type: application/json

{
  "content": [
    {
      "userId": 17,
      "lineOutDate": "2024-09-01",
      "reason": "ㅃㅃ"
    }
  ]
}

### 라인인
POST http://localhost:8080/api/v1/line-out-users/7/line-in

### 학년 전체 변경
POST http://localhost:8080/api/v1/user-grade-update
Content-Type: application/json

{
  "option": "DOWN"
}
