ifndef::snippets[]
:snippets: ../../../build/generated-snippets
endif::[]

= 그로잉 API 문서
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
:docinfo: shared-head

[[attendance]]
== 1. 출석

=== 1.1 출석 등록
operation::post-api-attendance[snippets='http-request,request-fields,http-response']

=== 1.2 출석 검색
operation::get-api-attendance-search[snippets='http-request,request-parameters,http-response,response-fields']

=== 1.3 코디별 주차 출석 검색
operation::get-api-attendance[snippets='http-request,request-parameters,http-response,response-fields']

=== 1.4 (통계) 결석/새가족 출석
operation::get-api-statistics-attendance[snippets='http-request,request-parameters,http-response,response-fields']

=== 1.5 (통계) 출석 진행 상황
operation::get-api-statistics-term-termId-attendanceProgress[snippets='http-request,path-parameters,request-parameters,http-response,response-fields']

=== 1.6 (통계) 출석 주차 개요
operation::get-api-statistics-attendanceSummary[snippets='http-request,request-parameters,http-response,response-fields']

=== 1.7 (엑셀) 전체 출석
operation::get-api-statistics-term-termId-personalAttendance[snippets='http-request,path-parameters,http-response,response-fields']

=== 1.7 (엑셀) 새가족 출석(등반 포함)
operation::get-api-statistics-term-termId-newFamilyAttendance[snippets='http-request,path-parameters,http-response,response-fields']

=== 1.8 (엑셀) 순모임별 출석
operation::get-api-statistics-term-termId-leaderAttendance[snippets='http-request,path-parameters,http-response,response-fields']

=== 1.9 (엑셀) 나무 모임 출석
operation::get-api-statistics-term-termId-managerAttendance[snippets='http-request,path-parameters,http-response,response-fields']

=== 1.10 (엑셀) 학년별 출석
operation::get-api-statistics-term-termId-gradeAttendance[snippets='http-request,path-parameters,http-response,response-fields']

=== 1.11 (엑셀) 텀 출석율(출석율 내림차순)
operation::get-api-statistics-term-termId-attendanceRate[snippets='http-request,path-parameters,http-response,response-fields']


[[auth]]
== 2. 권한

=== 2.1 로그인 여부 조회
operation::get-api-auth-isLoggedIn[snippets='http-request,http-response,response-fields']

=== 2.2 로그아웃
operation::post-api-auth-logout[snippets='http-request,http-response']

[[term]]
== 3. 텀

=== 3.1 텀의 코디 조회
operation::get-api-term-termId-cody[snippets='http-request,path-parameters,http-response,response-fields']

=== 3.2 텀의 새가족반 조회
operation::get-api-term-termId-newFamilyTeamLeaders[snippets='http-request,path-parameters,http-response,response-fields']

=== 3.3 코디 소속 순모임 조회
operation::get-api-term-termId-cody-codyId-leaders[snippets='http-request,path-parameters,http-response,response-fields']

=== 3.4 텀 목록 조회
operation::get-api-term[snippets='http-request,http-response,response-fields']

=== 3.5 주차별 재적인원, 새등록인원 조회
operation::get-api-term-totalUser[snippets='http-request,request-parameters,http-response,response-fields']

=== 3.6 텀 새가족 조회(이미 등반한 순원 포함)
operation::get-api-term-termId-newComers[snippets='http-request,path-parameters,http-response,response-fields']

=== 3.7 새가족 등록
operation::post-api-user[snippets='http-request,request-fields,http-response']

=== 3.8 새가족 등반
operation::post-api-team-teamId-teamMember-teamMemberId-lineup[snippets='http-request,path-parameters,request-fields,http-response']

=== 3.9 새가족 라인아웃
operation::post-api-team-teamId-teamMember-teamMemberId-lineout[snippets='http-request,path-parameters,request-fields,http-response']

[[user]]
== 4. 유저

=== 4.1 유저 전체 조회
operation::get-api-user[snippets='http-request,http-response,response-fields']

=== 4.2 유저 단건 조회
operation::get-api-user-userId[snippets='http-request,path-parameters,http-response,response-fields']

=== 4.3 내 정보 조회
operation::get-api-user-myInfo[snippets='http-request,http-response,response-fields']

=== 4.4 유저 정보 수정
operation::put-api-user-userId[snippets='http-request,path-parameters,request-fields,http-response']

[[training]]
== 5. 명부

=== 5.1 명부 생성
operation::post-api-training[snippets='http-request,request-fields,http-response']

=== 5.2 명부 인원 등록
operation::post-api-trainings-trainingId-registerMember[snippets='http-request,path-parameters,request-fields,http-response']

[[etc]]
== 100. 그 외

=== 100.1 열거형 조회
operation::get-api-common-enums[snippets='http-request,request-parameters,http-response,response-fields']


